#Hugo configuration
title = "qwesdfds"
baseURL = "https:\/\/ewrewr.cxvbef34.dsf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
